'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PersonaCompendium.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Persona_5_Velvet_Room_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Persona_5_Velvet_Room_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arsene
        '''Obariyon
        '''High Pixie
        '''Decarabia
        '''Legion
        '''Ose
        '''Bugs
        '''Dionysus
        '''Black Frost
        '''Vishnu
        '''Crystal Skull
        '''Satanael
        '''Jackolantern
        '''Jack Frost
        '''Nekomata
        '''Sandman
        '''Choronzon
        '''Queen Mab
        '''Rangda
        '''Surt
        '''Futsunushi
        '''Silky
        '''Apsaras
        '''Isis
        '''Kikuri Hime
        '''Scathach
        '''Sarasvati
        '''Skadi
        '''Cybele
        '''Empress
        '''Queens Necklace
        '''Yaksini
        '''Lamia
        '''Hariti
        '''Dakini
        '''Titania
        '''Kali
        '''Mother Harlot
        '''Emperor
        '''Eligor
        '''Setanta
        '''Thoth
        '''Okuninushi
        '''Barong
        '''King Frost
        '''Oberon
        '''Baal
        '''Odin
        '''Berith
        '''Orobas
        '''Phoenix
        '''Anzu
        '''Unicorn
        '''Daisoujou
        '''Forneus        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PersonasNoArcana() As String
            Get
                Return ResourceManager.GetString("PersonasNoArcana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PS4Wallpapers_com_Persona_5_4K_3840x2160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS4Wallpapers.com_Persona-5-4K-3840x2160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property VRTheme() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("VRTheme", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
